# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konfig < Formula
  desc ""
  homepage "https://github.com/navi-bot/konfig"
  version "0.1"

  on_macos do
    url "https://github.com/navi-bot/konfig/releases/download/v0.1/konfig_0.1_darwin_all.tar.gz"
    sha256 "c168a903eb316f4e9e18c809a0d09a608bedca4f5799866c6c2666b680d820de"

    def install
      bin.install "konfig"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/navi-bot/konfig/releases/download/v0.1/konfig_0.1_linux_arm64.tar.gz"
      sha256 "5646e7dde27b51223c816f2335e65ef36170c18faf451faa18515ff00beb7607"

      def install
        bin.install "konfig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/navi-bot/konfig/releases/download/v0.1/konfig_0.1_linux_amd64.tar.gz"
      sha256 "6a4b2f4dcf66bfef3ecbca4f89ae9ec2cc3899618bbeec09aeee7445957649cf"

      def install
        bin.install "konfig"
      end
    end
  end
end
